version: '3.6'
services:

  fastagi:
    #image: cnsoluciones/fastagi
    image: cnsoluciones/fastagi-dev
    container_name: fastagi
    hostname: fastagi
    restart: always
    ports:
      - 8000:8000
      - 8011:8011
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./code:/home/go/src/fastagi
      - ./build/fastagi/audios:/audios
    stdin_open: true
    tty: true

  voip:
    image: cnsoluciones/asterisk-iax2
    container_name: voip
    hostname: voip
    restart: always
    privileged: true
    ports:
      - 4569:4569/udp
    working_dir: /etc/asterisk
    depends_on:
      - fastagi 
    links:
      - fastagi
